[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_NEWS_API_KEY = "79da6f4b141d2e692cec0ce3523d71c1"
  NEXT_TELEMETRY_DISABLED = "1"